### ISSUE TITLE
使用inflate.py处理zip crypto deflate的压缩包

### ISSUE THREAD

**Issue by LEOGGMAGIC** [Aloxaf/rbkcrack#81]
回显这个错误。成功得到3个key，-d输出后png打不开，但看到使用说明里用inflate.py处理，可是一直报错
Traceback (most recent call last):
  File "inflate.py", line 15, in <module>
    main()
  File "inflate.py", line 12, in main
    sys.stdout.buffer.write(inflate(sys.stdin.buffer.read()))
  File "inflate.py", line 8, in inflate
    return zlib.decompress(data, -zlib.MAX_WBITS)
zlib.error: Error -3 while decompressing data: invalid stored block lengths

**Comment by functionxxx** [comment]
也许得出来的key是错的，导致输出的根本不是deflate流

我用同一个plainfile _(14byte header)_ 去算同一个zip内的两个不同文件，却分别得到两串不同的key。而且用该key输出后的文件只有前12byte与原文件一致，后面都是乱码

尝试用inflate.py处理，报一样的错

加`-u`选项，报corrupt deflate stream

用改造过的7za，直接报Wrong password

**Comment by Nixiabing** [comment]
同样的问题
